var searchData=
[
  ['kalmanfilter',['KalmanFilter',['../dd/d6a/classcv_1_1KalmanFilter.html',1,'cv']]],
  ['kaze',['KAZE',['../d3/d61/classcv_1_1KAZE.html',1,'cv']]],
  ['kdtreeindex',['KDTreeIndex',['../df/d36/classcvflann_1_1KDTreeIndex.html',1,'cvflann']]],
  ['kdtreeindexparams',['KDTreeIndexParams',['../d7/d99/structcvflann_1_1KDTreeIndexParams.html',1,'cvflann::KDTreeIndexParams'],['../d0/d99/structcv_1_1flann_1_1KDTreeIndexParams.html',1,'cv::flann::KDTreeIndexParams']]],
  ['kdtreesingleindex',['KDTreeSingleIndex',['../db/d92/classcvflann_1_1KDTreeSingleIndex.html',1,'cvflann']]],
  ['kdtreesingleindexparams',['KDTreeSingleIndexParams',['../d5/d2d/structcvflann_1_1KDTreeSingleIndexParams.html',1,'cvflann']]],
  ['kernel',['Kernel',['../dd/d4c/classcv_1_1ocl_1_1Kernel.html',1,'cv::ocl::Kernel'],['../d7/db8/classcv_1_1ml_1_1SVM_1_1Kernel.html',1,'cv::ml::SVM::Kernel']]],
  ['kernelarg',['KernelArg',['../d3/d17/classcv_1_1ocl_1_1KernelArg.html',1,'cv::ocl']]],
  ['kerneltag',['KernelTag',['../d4/d88/structcv_1_1detail_1_1KernelTag.html',1,'cv::detail']]],
  ['keypoint',['KeyPoint',['../d2/d29/classcv_1_1KeyPoint.html',1,'cv']]],
  ['keypointsfilter',['KeyPointsFilter',['../de/db2/classcv_1_1KeyPointsFilter.html',1,'cv']]],
  ['kl_5fdivergence',['KL_Divergence',['../d2/dc2/structcvflann_1_1KL__Divergence.html',1,'cvflann']]],
  ['kmeansdistancecomputer',['KMeansDistanceComputer',['../d7/d6e/classcvflann_1_1KMeansIndex_1_1KMeansDistanceComputer.html',1,'cvflann::KMeansIndex']]],
  ['kmeansindex',['KMeansIndex',['../df/d1f/classcvflann_1_1KMeansIndex.html',1,'cvflann']]],
  ['kmeansindexparams',['KMeansIndexParams',['../df/d7a/structcv_1_1flann_1_1KMeansIndexParams.html',1,'cv::flann::KMeansIndexParams'],['../de/dff/structcvflann_1_1KMeansIndexParams.html',1,'cvflann::KMeansIndexParams']]],
  ['knearest',['KNearest',['../dd/de1/classcv_1_1ml_1_1KNearest.html',1,'cv::ml']]],
  ['knnradiusuniqueresultset',['KNNRadiusUniqueResultSet',['../d3/dd8/classcvflann_1_1KNNRadiusUniqueResultSet.html',1,'cvflann']]],
  ['knnresultset',['KNNResultSet',['../d5/db2/classcvflann_1_1KNNResultSet.html',1,'cvflann']]],
  ['knnsimpleresultset',['KNNSimpleResultSet',['../d8/daa/classcvflann_1_1KNNSimpleResultSet.html',1,'cvflann']]],
  ['knnuniqueresultset',['KNNUniqueResultSet',['../d0/d5d/classcvflann_1_1KNNUniqueResultSet.html',1,'cvflann']]]
];
