var searchData=
[
  ['interface',['Interface',['../d1/d1b/group__core__hal__interface.html',1,'']]],
  ['inverse_20square_20root_20calculation',['Inverse square root calculation',['../d0/d5d/group__core__hal__interface__invSqrt.html',1,'']]],
  ['intel_20ipp_20asynchronous_20c_2fc_2b_2b_20converters',['Intel IPP Asynchronous C/C++ Converters',['../d6/dcf/group__core__ipp.html',1,'']]],
  ['intel_20va_2dapi_2fopencl_20_28cl_2dva_29_20interoperability',['Intel VA-API/OpenCL (CL-VA) interoperability',['../d1/daa/group__core__va__intel.html',1,'']]],
  ['image_20file_20reading_20and_20writing',['Image file reading and writing',['../d4/da8/group__imgcodecs.html',1,'']]],
  ['ios_20glue',['iOS glue',['../d2/d92/group__imgcodecs__ios.html',1,'']]],
  ['image_20processing',['Image Processing',['../d7/dbd/group__imgproc.html',1,'']]],
  ['imgproc_5fcolor_5fconversions',['Imgproc_color_conversions',['../d8/d01/group__imgproc__color__conversions.html',1,'']]],
  ['imgproc_5fcolormap',['Imgproc_colormap',['../d3/d50/group__imgproc__colormap.html',1,'']]],
  ['imgproc_5fdraw',['Imgproc_draw',['../d6/d6e/group__imgproc__draw.html',1,'']]],
  ['imgproc_5ffeature',['Imgproc_feature',['../dd/d1a/group__imgproc__feature.html',1,'']]],
  ['image_20filtering',['Image Filtering',['../d4/d86/group__imgproc__filter.html',1,'']]],
  ['imgproc_5fhal_5ffunctions',['Imgproc_hal_functions',['../d5/df1/group__imgproc__hal__functions.html',1,'']]],
  ['imgproc_5fhal_5finterface',['Imgproc_hal_interface',['../dd/d8b/group__imgproc__hal__interface.html',1,'']]],
  ['imgproc_5fhist',['Imgproc_hist',['../d6/dc7/group__imgproc__hist.html',1,'']]],
  ['imgproc_5fmisc',['Imgproc_misc',['../d7/d1b/group__imgproc__misc.html',1,'']]],
  ['imgproc_5fmotion',['Imgproc_motion',['../d7/df3/group__imgproc__motion.html',1,'']]],
  ['imgproc_5fobject',['Imgproc_object',['../df/dfb/group__imgproc__object.html',1,'']]],
  ['imgproc_5fshape',['Imgproc_shape',['../d3/dc0/group__imgproc__shape.html',1,'']]],
  ['imgproc_5fsubdiv2d',['Imgproc_subdiv2d',['../df/d5b/group__imgproc__subdiv2d.html',1,'']]],
  ['imgproc_5ftransform',['Imgproc_transform',['../da/d54/group__imgproc__transform.html',1,'']]],
  ['inpainting',['Inpainting',['../d7/d8b/group__photo__inpaint.html',1,'']]],
  ['images_20stitching',['Images stitching',['../d1/d46/group__stitching.html',1,'']]],
  ['image_20blenders',['Image Blenders',['../d9/d46/group__stitching__blend.html',1,'']]],
  ['images_20warping',['Images Warping',['../d0/dfa/group__stitching__warp.html',1,'']]],
  ['ios_20glue_20for_20video_20i_2fo',['iOS glue for video I/O',['../d5/d26/group__videoio__ios.html',1,'']]]
];
